### ISSUE TITLE
can't ssl

### ISSUE THREAD

**Issue by alekkxl** [patrikjuvonen/docker-nginx-http3#1]
nginx: [emerg] Read OCSP response file "/etc/nginx/" failed: -1 (SSL: error:02000015:system library:OPENSSL_internal:Is a directory error:11000002:BIO routines:OPENSSL_internal:system library)

**Comment by patrikjuvonen** [comment]
You have to generate the OCSP response yourself since it doesn't support it automatically.

https://knowledge.broadcom.com/external/article/42966/creating-and-using-an-ocsp-responder-for.html
