### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by githubcdr** [patrikjuvonen/docker-nginx-http3#3]
Hi,

First of all thanks for this nice image, we use it in production and it's working great!

We use renovate to check for new versions, currently it's hard to detect new versions since the docker tag is a hash.

Could you in the future release semver tagged versions?

Best regards,

**Comment by patrikjuvonen** [comment]
Thanks for the suggestion, I've now set up semver publishing, starting with version 2.0.0.
