### ISSUE TITLE
Update to nginx 1.27.0

### ISSUE THREAD

**Issue by quinncnl** [patrikjuvonen/docker-nginx-http3#7]
Hi!

Thanks for the nice image! Do you have plan to upgrade nginx to the latest version? There seems to be some nice fixes.
See https://[nginx.org/en/CHANGES](https://nginx.org/en/CHANGES)

**Comment by patrikjuvonen** [comment]
Hey, thanks for reaching out!

Nginx 1.26 stable comes with HTTP/3 support built-in so I think I'll deprecate this repository at some point as a custom build is no longer needed. The patches are also no longer maintained which would require more work to get up and running with the latest version.

However I might create a new repository for nginx with brotli and ModSecurity modules at some point.
