### ISSUE TITLE
v2.1.15 tags not available on registry

### ISSUE THREAD

**Issue by githubcdr** [patrikjuvonen/docker-nginx-http3#8]
Hi,

I see a v2.1.15 release but for some reason I can't pull it?

```
  Warning  Failed     21s (x3 over 60s)  kubelet            Failed to pull image "ghcr.io/patrikjuvonen/docker-nginx-http3:v2.1.15": rpc error: code = NotFound desc = failed to pull and unpack
 image "ghcr.io/patrikjuvonen/docker-nginx-http3:v2.1.15": no match for platform in manifest: not found
```

Might be related to x64 builds, since arm64 works

Anyways, thanks again for this great image :) 

cdr

**Comment by patrikjuvonen** [comment]
Hi, thanks for reporting the issue!

I'll re-run the build, it was stuck for a couple of days. I'll ping you here when it should be available.

**Comment by patrikjuvonen** [comment]
@githubcdr Should be fixed now!

**Comment by githubcdr** [comment]
It is, thanks man!
